name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: backend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # 시크릿 누락/공백 방지 + 정제
      - name: Check & sanitize DockerHub secrets
        shell: bash
        run: |
          set -euo pipefail
          u="${{ secrets.DOCKERHUB_USERNAME }}"
          t="${{ secrets.DOCKERHUB_TOKEN }}"
          [[ -n "$u" ]] || { echo "❌ DOCKERHUB_USERNAME missing"; exit 1; }
          [[ -n "$t" ]] || { echo "❌ DOCKERHUB_TOKEN missing"; exit 1; }
          u="$(printf %s "$u" | tr -d '[:space:]')"
          t="$(printf %s "$t" | tr -d '[:space:]')"
          echo "DH_USER=$u"  >> $GITHUB_ENV
          echo "DH_TOKEN=$t" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DH_USER }}
          password: ${{ env.DH_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DH_USER }}/meet-u-backend:latest
            ${{ env.DH_USER }}/meet-u-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DH_USER }}/meet-u-backend:buildcache
          cache-to:   type=registry,ref=${{ env.DH_USER }}/meet-u-backend:buildcache,mode=max

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 45m
          script: |
            set -euo pipefail
            cd ~/meet-u-career
            echo "${{ env.DH_TOKEN }}" | docker login -u "${{ env.DH_USER }}" --password-stdin
            docker compose pull backend
            docker compose up -d backend
            docker image prune -f
